__all__ = ["SigningException", "SignatureDecodeException", "SignatureVerificationException", "JWKException"]


class SigningException(Exception): ...


class SignatureDecodeException(SigningException): ...


class SignatureVerificationException(SigningException): ...


class JWKException(SigningException): ...
