class GzipCompressor:
    def __init__(self, level: int = 9) -> None: ...
    def compress(self, data: bytes, finish: bool) -> bytes: ...

class BrotliCompressor:
    def __init__(self, quality: int = 4, lgwin: int = 22) -> None: ...
    def compress(self, data: bytes, finish: bool) -> bytes: ...

def compress_bz2(data: bytes) -> bytes: ...
def decompress_bz2(data: bytes) -> bytes: ...
def compress_lzma(data: bytes) -> bytes: ...
def decompress_lzma(data: bytes) -> bytes: ...
def compress_zlib(data: bytes) -> bytes: ...
def decompress_zlib(data: bytes) -> bytes: ...
def compress_zstd(data: bytes) -> bytes: ...
def decompress_zstd(data: bytes) -> bytes: ...
