import typing as t

class Compressor:
    def __init__(self, format: str, **params: int) -> None: ...
    def compress(self, data: bytes, finish: bool) -> bytes: ...

def compress(data: bytes, format: str, **params: int) -> bytes: ...
def decompress(data: bytes, format: str) -> bytes: ...
def tar(directory: str, writer: t.BinaryIO, format: str | None = None) -> int: ...
def untar(data: bytes, directory: str, format: str | None = None) -> None: ...
