class GzipCompressor:
    def __init__(self, level: int = 9) -> None: ...
    def compress(self, data: bytes, finish: bool) -> bytes: ...

class BrotliCompressor:
    def __init__(self, quality: int = 4, lgwin: int = 22) -> None: ...
    def compress(self, data: bytes, finish: bool) -> bytes: ...
