class AsymmetricSigner:
    def __init__(self, algorithm: str) -> None: ...
    def sign(self, message: bytes, key: bytes) -> bytes: ...
    def verify(self, message: bytes, signature: bytes, key: bytes) -> bool: ...
    def generate(self) -> tuple[bytes, bytes]: ...
    def public_key(self, key: bytes) -> bytes: ...
