import contextlib
import os
import typing as t

import flama.schemas
from flama import types
from flama._core.json_encoder import encode_json
from flama.exceptions import FrameworkNotInstalled, HTTPException
from flama.http.responses.sse import ServerSentEventResponse
from flama.models.components import ModelComponentBuilder
from flama.models.resources.base import InspectMixin
from flama.resources import data_structures
from flama.resources.exceptions import ResourceAttributeNotFound, ResourceModelNotFound
from flama.resources.resource import Resource, ResourceType
from flama.resources.routing import ResourceRoute

if t.TYPE_CHECKING:
    from flama.models.base import MLModel
    from flama.models.components import ModelComponent

__all__ = ["BaseMLResource", "MLResource", "PredictMixin", "StreamMixin", "MLResourceType"]


Component = t.TypeVar("Component", bound="ModelComponent")


class PredictMixin:
    @classmethod
    def _add_predict(
        cls, name: str, verbose_name: str, model_model_type: type["MLModel"], **kwargs
    ) -> dict[str, t.Any]:
        @ResourceRoute.method("/predict/", methods=["POST"], name="predict")
        async def predict(
            self,
            model: model_model_type,  # ty: ignore[invalid-type-form]
            data: t.Annotated[types.Schema, types.SchemaMetadata(flama.schemas.schemas.ml.PredictInput)],
        ) -> t.Annotated[types.Schema, types.SchemaMetadata(flama.schemas.schemas.ml.PredictOutput)]:
            try:
                return {"output": model.predict(data["input"])}
            except FrameworkNotInstalled:
                raise
            except Exception as e:
                raise HTTPException(status_code=400, detail=str(e)) from e

        predict.__doc__ = f"""
            tags:
                - {verbose_name}
            summary:
                Generate a prediction
            description:
                Generate a prediction using the model from this resource.
            responses:
                200:
                    description:
                        The prediction generated by the model.
        """

        return {"_predict": predict}


class StreamMixin:
    @classmethod
    def _add_stream(cls, name: str, verbose_name: str, model_model_type: type["MLModel"], **kwargs) -> dict[str, t.Any]:
        @ResourceRoute.method("/stream/", methods=["POST"], name="stream")
        async def stream(
            self,
            model: model_model_type,  # ty: ignore[invalid-type-form]
            data: t.Annotated[types.Schema, types.SchemaMetadata(flama.schemas.schemas.ml.StreamInput)],
        ) -> ServerSentEventResponse:
            async def _encode():
                async for item in model.stream([data["input"]]):
                    yield encode_json(item, compact=True).decode()

            return ServerSentEventResponse(_encode())

        stream.__doc__ = f"""
            tags:
                - {verbose_name}
            summary:
                Stream predictions
            description:
                Stream predictions using the model from this resource via Server-Sent Events.
            responses:
                200:
                    description:
                        An SSE stream of prediction tokens.
        """

        return {"_stream": stream}


class MLResourceType(ResourceType, InspectMixin, PredictMixin, StreamMixin):
    METHODS = ("inspect", "predict", "stream")

    def __new__(mcs, name: str, bases: tuple[type], namespace: dict[str, t.Any]):
        """Resource metaclass for defining basic behavior for ML resources:
        * Create _meta attribute containing some metadata (model...).
        * Adds methods related to ML resource (inspect, predict...) listed in METHODS class attribute.

        :param name: Class name.
        :param bases: List of superclasses.
        :param namespace: Variables namespace used to create the class.
        """
        if not mcs._is_abstract(namespace):
            component = mcs._get_model_component(name, bases, namespace)
            namespace["component"] = component
            namespace["model"] = component.model

            namespace.setdefault("_meta", data_structures.Metadata()).namespaces["model"] = {
                "component": component,
                "model": component.model,
                "model_type": component.get_model_type(),
            }

        return super().__new__(mcs, name, bases, namespace)

    @staticmethod
    def _is_abstract(namespace: dict[str, t.Any]) -> bool:
        return namespace.get("__module__") == "flama.models.resources.ml" and namespace.get("__qualname__") in (
            "BaseMLResource",
            "MLResource",
        )

    @classmethod
    def _get_model_component(cls, name: str, bases: t.Sequence[t.Any], namespace: dict[str, t.Any]) -> "ModelComponent":
        with contextlib.suppress(ResourceAttributeNotFound):
            return cls._get_attribute(name, "component", bases, namespace, metadata_namespace="model")

        with contextlib.suppress(ResourceAttributeNotFound):
            return ModelComponentBuilder.build(
                cls._get_attribute(name, "model_path", bases, namespace, metadata_namespace="model")
            )

        raise ResourceModelNotFound(name=name)


class BaseMLResource(Resource, t.Generic[Component], metaclass=MLResourceType):
    component: Component
    model: t.Any
    model_path: str | os.PathLike


class MLResource(BaseMLResource["ModelComponent"]): ...
