#!/bin/bash
set -e

# ─── Check ───────────────────────────────────────────────────────────────────

UV_URL="https://astral.sh/uv/install.sh"

install_uv() {
  echo "⚠️  UV is not available"
  while true; do
    read -p "Do you wish to install it? (Y/N/q): " yn
    case $yn in
    [Yy]*)
      curl -LsSf $UV_URL | sh
      echo "✅ UV installation completed ($(uv --version))"
      break
      ;;
    [Nn]*)
      echo "❌ UV will not be installed"
      echo "💡 The development team recommends installing UV for packaging and dependency management"
      exit 1
      ;;
    [q]*)
      exit 0
      ;;
    *) echo "Please answer yes (Y) or no (N)" ;;
    esac
  done
}

run_check() {
  echo "🔍 Checking dependencies..."

  if ! command -v uv &>/dev/null; then
    install_uv
  else
    echo "✅ UV is available ($(uv --version))"
  fi
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  run_check "$@"
fi
