#!/usr/bin/env bash

install_pkg()
{
  echo "🔥 Install python requirements..."
  poetry install "$@"
  cd templates
  echo "🔥 Install js requirements..."
  npm i
  echo "🔥 Build templates..."
  npm run build
  cd ..
}

install_pkg "$@"