#!/usr/bin/env bash
set -e

run_mypy() {
  echo "• Run MyPy code formatting:"
  poetry run mypy --install-types --non-interactive "$@"
  echo "↳ MyPy done"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  run_mypy "$@"
fi
