#!/bin/bash
set -e

# ─── Test ────────────────────────────────────────────────────────────────────

run_test() {
  echo "🧪 Testing project..."
  uv run pytest -n auto "$@"
  echo "✅ Test complete."
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  run_test "$@"
fi
