#!/usr/bin/env bash
set -e

source scripts/str_lib.sh

test() {
  message "info" "Tests"
  uv run pytest -n auto
  message "success" "Tests completed"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  test "$@"
fi

