#!/usr/bin/env bash
set -e

run_pyright() {
  echo "• Run Pyright static types check:"
  poetry run pyright "$@"
  echo "↳ Pyright done"
}

if [[ "${#BASH_SOURCE[@]}" -eq 1 ]]; then
  run_pyright "$@"
fi
