import os
import pathlib
import typing as t

from flama.injection import Component
from flama.models.base import BaseModel, LLMModel, MLModel
from flama.models.engine.llm.decoder.decoder import Decoder
from flama.serialize.serializer import Serializer

__all__ = ["ModelComponent", "ModelComponentBuilder"]

M = t.TypeVar("M", bound=BaseModel)


class ModelComponent(Component, t.Generic[M]):
    """Thin DI wrapper around a packaged model.

    Construction is cheap: the wrapped :class:`~flama.models.base.BaseModel` owns the lazy
    deserialisation tiers (meta / artifacts / backend); this class only exposes them to the
    application's dependency-injection runtime and forwards lifecycle hooks. The model itself is
    materialised on :meth:`load` (sync) or :meth:`startup` (async), typically registered on
    ``app.events.startup`` so heavy work runs after uvicorn binds the port.
    """

    def __init__(self, model: M, /) -> None:
        """Bind the component to *model*.

        :param model: The wrapped :class:`~flama.models.base.BaseModel`. May be either eagerly
            populated (backend / meta / artifacts pre-supplied) or fully lazy.
        """
        self._model = model

    @property
    def model(self) -> M:
        """The wrapped model. Always non-``None``; never triggers deserialisation by itself."""
        return self._model

    def get_model_type(self) -> type[M]:
        """Return the concrete model class bound to this component.

        Used by :class:`~flama.models.modules.ModelsModule` to dispatch to the right resource
        class without materialising the model.
        """
        return type(self._model)

    def resolve(self) -> M:
        """Return the wrapped model for DI consumers.

        Specific subclasses generated by :func:`_component_for` override this with a narrower
        return annotation so the DI runtime picks the right component for each typed parameter.
        """
        return self._model

    def load(self) -> None:
        """Synchronously materialise the model; idempotent."""
        self._model.load()

    async def startup(self) -> None:
        """Run the model's async startup hook; idempotent."""
        await self._model.startup()


def _component_for(model_class: type[M]) -> type[ModelComponent[M]]:
    """Create a :class:`ModelComponent` subclass whose ``resolve`` return annotation is *model_class*.

    The DI runtime keys components by the return annotation of :meth:`resolve`; each registered
    model needs its own component subclass so the right typed parameter dispatches to the right
    artifact.
    """

    class SpecificModelComponent(ModelComponent):
        def resolve(self) -> model_class:  # ty: ignore[invalid-type-form]
            return super().resolve()

    return SpecificModelComponent


class ModelComponentBuilder:
    """Auto-dispatching builder for :class:`ModelComponent` instances.

    Reads the artifact metadata header to pick the right model class (:class:`MLModel` vs :class:`LLMModel`) by
    branching on :attr:`Metadata.framework.family`, creates a per-instance subclass of it so each registered model
    lands on its own typed component, and returns it without deserialising the artifact body or importing any backend
    module. The actual backend lookup happens at :meth:`ModelComponent.load` /
    :meth:`ModelComponent.startup` via :meth:`~flama.models.engine.backend.Backend.from_model_artifact`.
    The ``decoder`` and ``params`` kwargs are LLM-only and rejected at build time when paired with an ML artifact.
    """

    @staticmethod
    def build(
        p: str | os.PathLike | pathlib.Path,
        /,
        *,
        name: str = "model",
        decoder: Decoder | None = None,
        params: dict[str, t.Any] | None = None,
        autoload: bool = False,
    ) -> ModelComponent[LLMModel] | ModelComponent[MLModel]:
        """Build a lazy :class:`ModelComponent` from a packaged model artifact.

        Reads the artifact's metadata header (cheap) to dispatch to the right model class via
        :attr:`Metadata.framework.family`. The model body is **not** deserialised and no
        backend module is imported here; both are deferred to :meth:`ModelComponent.load` /
        :meth:`ModelComponent.startup`.

        :param p: Filesystem path to the packaged model artifact.
        :param name: Human-readable identifier surfaced on the model and in logs.
        :param decoder: Optional :class:`Decoder` configuration (LLM only). Rejected at build
            time when paired with a non-LLM artifact.
        :param params: Optional default generation parameters (LLM only). Forwarded to
            :meth:`LLMModel.configure` after construction; rejected at build time when paired
            with a non-LLM artifact.
        :param autoload: If ``True``, the wrapped model auto-loads on first :attr:`backend`
            access. Reserved for single-threaded callers (CLI); :meth:`ModelComponent.load` /
            :meth:`ModelComponent.startup` is the canonical path for the application lifespan.
        :return: A :class:`ModelComponent` wrapping the right :class:`MLModel` / :class:`LLMModel`.
        :raises ValueError: If *decoder* or *params* is set for a non-LLM artifact.
        """
        meta = Serializer.meta(path=p)
        path = pathlib.Path(str(p))

        if meta.framework.family == "llm":
            llm_class = t.cast("type[LLMModel]", type(LLMModel.__name__, (LLMModel,), {}))
            model = llm_class(meta=meta, name=name, path=path, autoload=autoload, decoder=decoder)
            if params:
                model.configure(params)
            return _component_for(llm_class)(model)

        if decoder is not None:
            raise ValueError("'decoder' is not supported by ML artifacts")
        if params is not None:
            raise ValueError("'params' is not supported by ML artifacts")

        ml_class = t.cast("type[MLModel]", type(MLModel.__name__, (MLModel,), {}))
        return _component_for(ml_class)(ml_class(meta=meta, name=name, path=path, autoload=autoload))
