import os
import typing as t

import flama.schemas
from flama import types
from flama._core.json_encoder import encode_json
from flama.http.responses.sse import ServerSentEventResponse
from flama.models.components import ModelComponentBuilder
from flama.resources import data_structures
from flama.resources.exceptions import ResourceAttributeError
from flama.resources.resource import Resource, ResourceType
from flama.resources.routing import ResourceRoute

if t.TYPE_CHECKING:
    from flama.models.base import BaseModel
    from flama.models.components import ModelComponent

__all__ = ["BaseModelResource", "ModelResource", "InspectMixin", "PredictMixin", "StreamMixin", "ModelResourceType"]


Component = t.TypeVar("Component", bound="ModelComponent")


class InspectMixin:
    @classmethod
    def _add_inspect(
        cls, name: str, verbose_name: str, model_model_type: type["BaseModel"], **kwargs
    ) -> dict[str, t.Any]:
        @ResourceRoute.method("/", methods=["GET"], name="inspect")
        async def inspect(self, model: model_model_type):  # ty: ignore[invalid-type-form]
            return model.inspect()

        inspect.__doc__ = f"""
            tags:
                - {verbose_name}
            summary:
                Retrieve the model
            description:
                Retrieve the model from this resource.
            responses:
                200:
                    description:
                        The model.
        """

        return {"_inspect": inspect}


class PredictMixin:
    @classmethod
    def _add_predict(
        cls, name: str, verbose_name: str, model_model_type: type["BaseModel"], **kwargs
    ) -> dict[str, t.Any]:
        @ResourceRoute.method("/predict/", methods=["POST"], name="predict")
        async def predict(
            self,
            model: model_model_type,  # ty: ignore[invalid-type-form]
            data: t.Annotated[types.Schema, types.SchemaMetadata(flama.schemas.schemas.MLModelPredictInput)],
        ) -> t.Annotated[types.Schema, types.SchemaMetadata(flama.schemas.schemas.MLModelPredictOutput)]:
            return {"output": model.predict(data["input"])}

        predict.__doc__ = f"""
            tags:
                - {verbose_name}
            summary:
                Generate a prediction
            description:
                Generate a prediction using the model from this resource.
            responses:
                200:
                    description:
                        The prediction generated by the model.
        """

        return {"_predict": predict}


class StreamMixin:
    @classmethod
    def _add_stream(
        cls, name: str, verbose_name: str, model_model_type: type["BaseModel"], **kwargs
    ) -> dict[str, t.Any]:
        @ResourceRoute.method("/stream/", methods=["POST"], name="stream")
        async def stream(
            self,
            model: model_model_type,  # ty: ignore[invalid-type-form]
            data: t.Annotated[types.Schema, types.SchemaMetadata(flama.schemas.schemas.MLModelStreamInput)],
        ) -> ServerSentEventResponse:
            async def _input():
                yield data["input"]

            async def _encode():
                async for item in model.stream(_input()):
                    yield encode_json(item, compact=True).decode()

            return ServerSentEventResponse(_encode())

        stream.__doc__ = f"""
            tags:
                - {verbose_name}
            summary:
                Stream predictions
            description:
                Stream predictions using the model from this resource via Server-Sent Events.
            responses:
                200:
                    description:
                        An SSE stream of prediction tokens.
        """

        return {"_stream": stream}


class ModelResourceType(ResourceType, InspectMixin, PredictMixin, StreamMixin):
    METHODS = ("inspect", "predict", "stream")

    def __new__(mcs, name: str, bases: tuple[type], namespace: dict[str, t.Any]):
        """Resource metaclass for defining basic behavior for ML resources:
        * Create _meta attribute containing some metadata (model...).
        * Adds methods related to ML resource (inspect, predict...) listed in METHODS class attribute.

        :param name: Class name.
        :param bases: List of superclasses.
        :param namespace: Variables namespace used to create the class.
        """
        if not mcs._is_abstract(namespace):
            try:
                # Get model component
                component = mcs._get_model_component(bases, namespace)
                namespace["component"] = component
                namespace["model"] = component.model
            except AttributeError as e:
                raise ResourceAttributeError(str(e), name)

            namespace.setdefault("_meta", data_structures.Metadata()).namespaces["model"] = {
                "component": component,
                "model": component.model,
                "model_type": component.get_model_type(),
            }

        return super().__new__(mcs, name, bases, namespace)

    @staticmethod
    def _is_abstract(namespace: dict[str, t.Any]) -> bool:
        return namespace.get("__module__") == "flama.models.resource" and namespace.get("__qualname__") in (
            "BaseModelResource",
            "ModelResource",
        )

    @classmethod
    def _get_model_component(cls, bases: t.Sequence[t.Any], namespace: dict[str, t.Any]) -> "ModelComponent":
        try:
            component: ModelComponent = cls._get_attribute("component", bases, namespace, metadata_namespace="model")
            return component
        except AttributeError:
            ...

        try:
            return ModelComponentBuilder.load(
                cls._get_attribute("model_path", bases, namespace, metadata_namespace="model")
            )
        except AttributeError:
            ...

        raise AttributeError(ResourceAttributeError.MODEL_NOT_FOUND)


class BaseModelResource(Resource, t.Generic[Component], metaclass=ModelResourceType):
    component: Component
    model: t.Any
    model_path: str | os.PathLike


class ModelResource(BaseModelResource["ModelComponent"]): ...
